// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCgrRuJhT4W63knfw2JU7o0_jXdB35wcI',
    appId: '1:90888433148:web:238948fe9e049edd035679',
    messagingSenderId: '90888433148',
    projectId: 'gem-record',
    authDomain: 'gem-record.firebaseapp.com',
    storageBucket: 'gem-record.appspot.com',
    measurementId: 'G-1WGSSVYVVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaIgkcjAt0mYuZ81muTjQ-n2envwO7XzQ',
    appId: '1:90888433148:android:89dc813025dc4c57035679',
    messagingSenderId: '90888433148',
    projectId: 'gem-record',
    storageBucket: 'gem-record.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOtzaiiau-CDJ9eM8oBJmfrZB0K_NOR14',
    appId: '1:90888433148:ios:ed7acb251faf2871035679',
    messagingSenderId: '90888433148',
    projectId: 'gem-record',
    storageBucket: 'gem-record.appspot.com',
    iosClientId: '90888433148-beq3a1ainvofc6348sh5igiana90rvlo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gemsRecords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOtzaiiau-CDJ9eM8oBJmfrZB0K_NOR14',
    appId: '1:90888433148:ios:ed7acb251faf2871035679',
    messagingSenderId: '90888433148',
    projectId: 'gem-record',
    storageBucket: 'gem-record.appspot.com',
    iosClientId: '90888433148-beq3a1ainvofc6348sh5igiana90rvlo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gemsRecords',
  );
}
